version: '3'

services:
  php:
    build:
      context: .
    container_name: market-php
    volumes:
      - .:/var/www/html
    ports:
      - 8989:80
  mysql:
    container_name: market-db
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=marketDB
      - MYSQL_USER=marketUser
      - MYSQL_PASSWORD=market